import React from 'react';
import { Link } from 'react-router-dom';
import { Brain, Zap, BarChart3, FileText, Mic, Shield, ArrowRight, CheckCircle, Star } from 'lucide-react';

const features = [
  { icon: Brain, title: 'AI-Powered Questions', desc: 'Dynamic questions generated by GPT-4 based on your role, difficulty, and interview type.', color: 'violet' },
  { icon: BarChart3, title: 'Real-time Evaluation', desc: 'Get scored on technical accuracy, communication clarity, and problem-solving ability instantly.', color: 'cyan' },
  { icon: FileText, title: 'Resume Analyzer', desc: 'Upload your resume and get AI-powered feedback on skills, gaps, and improvements.', color: 'green' },
  { icon: Mic, title: 'Voice Interview', desc: 'Answer using your microphone. Speech-to-text powered by Web Speech API.', color: 'orange' },
  { icon: Shield, title: 'Performance Reports', desc: 'Detailed reports with strengths, weaknesses, and personalized study recommendations.', color: 'pink' },
  { icon: Zap, title: 'Multiple Roles', desc: 'Practice for Frontend, Backend, Full Stack, Data Science, AI Engineer, and more.', color: 'amber' },
];

const stats = [
  { value: '10K+', label: 'Interviews Conducted' },
  { value: '95%', label: 'User Satisfaction' },
  { value: '7', label: 'Job Roles Supported' },
  { value: '4.9★', label: 'Average Rating' },
];

const colorMap = {
  violet: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
  cyan: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  green: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  orange: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
  pink: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
  amber: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
};

export default function LandingPage() {
  return (
    <div className="min-h-screen">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-white/10">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between h-16">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-violet-500 rounded-lg flex items-center justify-center">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <span className="font-display font-bold text-white text-lg">Interview<span className="text-violet-400">AI</span></span>
          </div>
          <div className="flex items-center gap-4">
            <Link to="/login" className="text-white/60 hover:text-white text-sm font-medium transition-colors">Log In</Link>
            <Link to="/register" className="btn-primary text-sm py-2 px-4">Get Started Free</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6 text-center relative overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-violet-600/10 rounded-full blur-[120px] pointer-events-none" />
        
        <div className="relative max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-violet-500/30 text-violet-300 text-sm font-medium mb-8">
            <Zap className="w-4 h-4" />
            Powered by Gemini· Real-time AI evaluation
          </div>

          <h1 className="text-6xl md:text-8xl font-display font-bold text-white leading-[0.9] tracking-tight mb-6">
            Ace every
            <span className="gradient-text block">interview</span>
            with AI
          </h1>

          <p className="text-xl text-white/50 max-w-2xl mx-auto mb-10 leading-relaxed">
            Simulate real job interviews, get instant AI feedback, and build confidence 
            before the actual interview. Used by thousands of developers worldwide.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/register" className="btn-primary flex items-center gap-2 text-base">
              Start Free Interview <ArrowRight className="w-5 h-5" />
            </Link>
            <Link to="/login" className="btn-secondary text-base">
              Sign In
            </Link>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mt-16">
            {stats.map((s) => (
              <div key={s.label} className="glass-card text-center">
                <div className="text-3xl font-bold text-white font-display">{s.value}</div>
                <div className="text-white/40 text-sm mt-1">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Everything you need to prepare</h2>
            <p className="text-white/40 text-lg max-w-2xl mx-auto">A complete interview preparation platform powered by cutting-edge AI technology.</p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon: Icon, title, desc, color }) => (
              <div key={title} className="glass-card group hover:bg-white/10 transition-all duration-300 hover:-translate-y-1">
                <div className={`w-12 h-12 rounded-xl border flex items-center justify-center mb-4 ${colorMap[color]}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <h3 className="text-white font-semibold text-lg mb-2">{title}</h3>
                <p className="text-white/40 text-sm leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center glass-card relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-violet-600/20 to-cyan-600/10 rounded-2xl" />
          <div className="relative">
            <h2 className="text-4xl font-display font-bold text-white mb-4">Ready to ace your next interview?</h2>
            <p className="text-white/50 mb-8">Join thousands of developers who've boosted their interview performance with InterviewAI.</p>
            <Link to="/register" className="btn-primary inline-flex items-center gap-2">
              Start For Free <ArrowRight className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 py-8 px-6 text-center text-white/30 text-sm">
        <div className="flex items-center justify-center gap-2 mb-2">
          <Brain className="w-4 h-4 text-violet-400" />
          <span className="font-semibold text-white/50">InterviewAI</span>
        </div>
        © 2024 InterviewAI. Built with React, Node.js, and OpenAI.
      </footer>
    </div>
  );
}
